---
platform: linux

image: docker:///concourse/pool-resource-test

inputs:
  - name: pool-resource
    path: gopath/src/github.com/concourse/pool-resource

run:
  path: gopath/src/github.com/concourse/pool-resource/ci/build
